### ISSUE TITLE
Support for multiple databases

### ISSUE THREAD

**Issue by iagorl** [mariusandra/insights#4]
It is on the plan the support for multiple databases? 

We would love to help on that :)

**Comment by jamesdean11** [comment]
Need to touch base about the whole base knowledge of the curriculum and the codes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mariusandra** [comment]
Hey @asurancetturix , can you clarify what you mean? Any of these?

- simultaneously connecting to multiple databases? 
- ... without merging data from them into reports?
- ... and merging data from them into reports?
- connecting to different database types?

**Comment by jamesdean11** [comment]
What would you like help with?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jamesdean11** [comment]
Sure is

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mariusandra** [comment]
@jamesdean11 I'm not really sure what you're saying :). But for things to help with, there's a list in the README called "Coming soon". Feel free to work on anything from there... or just anything you think would make the product better.
