### ISSUE TITLE
Insights as Rails engine

### ISSUE THREAD

**Issue by Jamevidi** [mariusandra/insights#9]
Great job with the gem!

Would insights maybe work as a Rails engine as well?...with some extra work. 

Thanks,

**Comment by mariusandra** [comment]
Hey, thanks!

It should be possible indeed... but I've decided to take this repo in a slightly different direction. I'm currently rewriting the backend in JS. 

The end goal is to have an app that's very lightweight, very performant (doesn't need a server with 2GB RAM) and can be extended and upgraded as easily as atom, vscode, wordpress and/or jenkins.

After this rewrite, a Rails engine or just a gem approach is definitely still possible, but unlikely.
